---
- name: create plugin directory
  file:
    path: "{{ rabbitmq_plugin_dir }}"
    owner: rabbitmq
    group: rabbitmq
    mode: "0755"
    state: directory
  become: true

- name: download plugins
  get_url:
    url: "{{ item.url }}"
    dest: "{{ rabbitmq_plugin_dir }}"
    owner: rabbitmq
    group: rabbitmq
    mode: "0640"
  become: true
  with_items: "{{ rabbitmq_plugins }}"
  when: not item.extract | default(True) | bool

- name: download and extract plugins
  unarchive:
    src: "{{ item.url }}"
    dest: "{{ rabbitmq_plugin_dir }}"
    owner: rabbitmq
    group: rabbitmq
    mode: "0640"
  become: true
  with_items: "{{ rabbitmq_plugins }}"
  when: item.extract | default(True) | bool

- name: enable rabbitmq plugins
  rabbitmq_plugin:
    names: "{{ item.name }}"
    state: enabled
  become: true
  with_items: "{{ rabbitmq_plugins }}"
